import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import AuthProvider from "@/services/AuthProvider";
import "./globals.css";

export const metadata = {
  title: "BabelForge",
  description: "Generated by BabelForge Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
